// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoTestObj.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoTestObj.proto</summary>
public static partial class ProtoTestObjReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoTestObj.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoTestObjReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJQcm90b1Rlc3RPYmoucHJvdG8iQwoMUHJvdG9UZXN0T2JqEg8KB1NvbWVJ",
          "bnQYASABKAUSEAoIU29tZVRleHQYAiABKAkSEAoIU29tZUJvb2wYAyABKAhi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoTestObj), global::ProtoTestObj.Parser, new[]{ "SomeInt", "SomeText", "SomeBool" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ProtoTestObj : pb::IMessage<ProtoTestObj> {
  private static readonly pb::MessageParser<ProtoTestObj> _parser = new pb::MessageParser<ProtoTestObj>(() => new ProtoTestObj());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoTestObj> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoTestObjReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoTestObj() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoTestObj(ProtoTestObj other) : this() {
    someInt_ = other.someInt_;
    someText_ = other.someText_;
    someBool_ = other.someBool_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoTestObj Clone() {
    return new ProtoTestObj(this);
  }

  /// <summary>Field number for the "SomeInt" field.</summary>
  public const int SomeIntFieldNumber = 1;
  private int someInt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int SomeInt {
    get { return someInt_; }
    set {
      someInt_ = value;
    }
  }

  /// <summary>Field number for the "SomeText" field.</summary>
  public const int SomeTextFieldNumber = 2;
  private string someText_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SomeText {
    get { return someText_; }
    set {
      someText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "SomeBool" field.</summary>
  public const int SomeBoolFieldNumber = 3;
  private bool someBool_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool SomeBool {
    get { return someBool_; }
    set {
      someBool_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoTestObj);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoTestObj other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SomeInt != other.SomeInt) return false;
    if (SomeText != other.SomeText) return false;
    if (SomeBool != other.SomeBool) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (SomeInt != 0) hash ^= SomeInt.GetHashCode();
    if (SomeText.Length != 0) hash ^= SomeText.GetHashCode();
    if (SomeBool != false) hash ^= SomeBool.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (SomeInt != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(SomeInt);
    }
    if (SomeText.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(SomeText);
    }
    if (SomeBool != false) {
      output.WriteRawTag(24);
      output.WriteBool(SomeBool);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (SomeInt != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SomeInt);
    }
    if (SomeText.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SomeText);
    }
    if (SomeBool != false) {
      size += 1 + 1;
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoTestObj other) {
    if (other == null) {
      return;
    }
    if (other.SomeInt != 0) {
      SomeInt = other.SomeInt;
    }
    if (other.SomeText.Length != 0) {
      SomeText = other.SomeText;
    }
    if (other.SomeBool != false) {
      SomeBool = other.SomeBool;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          SomeInt = input.ReadInt32();
          break;
        }
        case 18: {
          SomeText = input.ReadString();
          break;
        }
        case 24: {
          SomeBool = input.ReadBool();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
